"""delete show.meme column

Revision ID: 2a4684db6517
Revises: f21e32753592
Create Date: 2025-02-05 12:11:25.097894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4684db6517'
down_revision: Union[str, None] = 'f21e32753592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'meme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('meme', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
